org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
kotlin.daemon.jvm.options=-Xmx1500m -Xms256m
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=true
